# Generated by Django 2.0 on 2018-02-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180124_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articleName',
        ),
    ]
