# Generated by Django 2.0 on 2018-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_article_articlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='fileName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
